### ISSUE TITLE
New data products checklist

### ISSUE THREAD

**Issue by objornsson** [MODA-NYC/db-safegraph#105]
Moving from RDP repo (sorry!)
- [ ]  Re-establish normalization product for Parks
- [ ]  Distance from home
- [ ]  Visits to BIDs
- [ ]  Visits to CBDs
- [ ]  Business openings and closures

**Comment by cnicklin** [comment]
Note: on hold until new Safegraph pipeline is fully implemented

**Comment by SteveScott** [comment]
making progress on this with neighborhood patterns.
